#finding quads
Q = 0
sQ = 0
Q2 = ["2h", "2d", "2c", "2s"]
Q3 = ["3h", "3d", "3c", "3s"]
Q4 = ["4h", "4d", "4c", "4s"]
Q5 = ["5h", "5d", "5c", "5s"]
Q6 = ["6h", "6d", "6c", "6s"]
Q7 = ["7h", "7d", "7c", "7s"]
Q8 = ["8h", "8d", "8c", "8s"]
Q9 = ["9h", "9d", "9c", "9s"]
Q10 = ["10h", "10d", "10c", "10s"]
Q11 = ["Jh", "Jd", "Jc", "Js"]
Q12 = ["Qh", "Qd", "Qc", "Qs"]
Q13 = ["Kh", "Kd", "Kc", "Ks"]
Q14= ["Ah", "Ad", "Ac", "As"]
def quads(lst):
    q2 = len(list(set(lst) & set(Q2)))
    if q2 >= 4:
        global Q
        global sQ
        Q = 1
        sQ = 8
    q3 = len(list(set(lst) & set(Q3)))
    if q3 >= 4:
        Q = 1
        sQ = 12
    q4 = len(list(set(lst) & set(Q4)))
    if q4 >= 4:
        Q = 1
        sQ = 16
    q5 = len(list(set(lst) & set(Q5)))
    if q5 >= 4:
        Q = 1
        sQ = 20
    q6 = len(list(set(lst) & set(Q6)))
    if q6 >= 4:
        Q = 1
        sQ = 24
    q7 = len(list(set(lst) & set(Q7)))
    if q7 >= 4:
        Q = 1
        sQ = 28
    q8 = len(list(set(lst) & set(Q8)))
    if q8 >= 4:
        Q = 1
        sQ = 32
    q9 = len(list(set(lst) & set(Q9)))
    if q9 >= 4:
        Q = 1
        sQ = 36
    q10 = len(list(set(lst) & set(Q10)))
    if q10 >= 4:
        Q = 1
        sQ = 40
    q11 = len(list(set(lst) & set(Q11)))
    if q11 >= 4:
        Q = 1
        sQ = 44
    q12 = len(list(set(lst) & set(Q12)))
    if q12 >= 4:
        Q = 1
        sQ = 48
    q13 = len(list(set(lst) & set(Q13)))
    if q13 >= 4:
        Q = 1
        sQ = 52
    q14 = len(list(set(lst) & set(Q14)))
    if q14 >= 4:
        Q = 1
        sQ = 56
   

